[config]

[green_agent]
agentbeats_id = "019c7b74-4444-7b32-9b78-0f5778529c3c"

[green_agent.env]

[[participants]]
agentbeats_id = "019c7ac7-e78f-7c90-9d0a-403054e04331"
name = "agent1"

[participants.env]
a = "${a}"
c = "${c}"