[config]
agent_llm = "gpt-4.1"
domain = "airline"
num_tasks = 5
num_trials = 1
user_llm = "gpt-4.1"

[green_agent]
agentbeats_id = "019c75d3-31c3-7003-9806-936cf037c04c"

[green_agent.env]

[[participants]]
agentbeats_id = "019c7612-76c5-7911-8b17-fea8c8a28757"
name = "agent"

[participants.env]